name: Mario Grossenbacher
favicon: null
layout_spectrum: 0.8711173799820244
typography_spectrum: 0.14143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed8c2e'
    - '#ffffff'
    - '#060c0e'
    - '#8b8b89'
    - '#353439'
  brandStrength: 0.23361237277276814
  lightness: 0.7949617654085159
  saturation: 0.23020185250788927
  rhythmicContrast: 0
purpose: []
