name: Mario Grossenbacher
favicon: null
layout_spectrum: 0.76361
typography_spectrum: 0.387218
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed8c2e'
    - '#ffffff'
    - '#060c0e'
    - '#8b8b89'
    - '#353439'
  brandStrength: 0.2336123727727681
  lightness: 0.7949617654085159
  saturation: 0.2302018525078893
  rhythmicContrast: 0
purpose: []
